### ISSUE TITLE
[Bug Report]:  Entity Damage error

### ISSUE THREAD

**Issue by MatinHQ** [Crazy-Crew/CrazyEnchantments#800]
### Server Version

1.20.1

### Server Platform

Purpur

### Describe the bug

I am using latest build with purpur 1.20.1 and this error spams on console

```
[20:08:42 ERROR]: Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v2.2.7
java.lang.NoSuchMethodError: 'org.bukkit.damage.DamageSource org.bukkit.event.entity.EntityDamageEvent.getDamageSource()'
        at com.badbones69.crazyenchantments.paper.listeners.FireworkDamageListener.onFireworkDamage(FireworkDamageListener.java:26) ~[CrazyEnchantments-Paper-2.2.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1291.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2062]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:264) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1227) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1080) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1023) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1261) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2260) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1099) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1479) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1006) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1166) ~[?:?]
        at net.minecraft.world.entity.Mob.doHurtTarget(Mob.java:1714) ~[?:?]
        at net.minecraft.world.entity.monster.warden.Warden.doHurtTarget(Warden.java:238) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.world.entity.ai.behavior.MeleeAttack.lambda$create$0(MeleeAttack.java:21) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.declarative.BehaviorBuilder$1.trigger(BehaviorBuilder.java:42) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.world.entity.ai.behavior.OneShot.tryStart(OneShot.java:17) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.world.entity.ai.Brain.startEachNonRunningBehavior(Brain.java:432) ~[?:?]
        at net.minecraft.world.entity.ai.Brain.tick(Brain.java:389) ~[?:?]
        at net.minecraft.world.entity.monster.warden.Warden.customServerAiStep(Warden.java:305) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:966) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3442) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:704) ~[?:?]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3097) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:460) ~[?:?]
        at net.minecraft.world.entity.monster.warden.Warden.tick(Warden.java:268) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1435) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:896) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:873) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1585) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

### Crate Type

None

### Steps to reproduce

Nothing special just purpur 1.20.1 and few players 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
Update to 1.20.4 if that much of an issue, All your plugins will likely work and if not they have updates for said plugins by now.

We won't be maintaining multiple versions of CrazyEnchantments nor re-introducing version checks.
